#!/usr/bin/perl -w
use strict;
use warnings;

for my $OPTION_IGNORE_OUTSTATION_SEQ_ON_REQUEST_SESSION_INITIATION   (0, 1) {
for my $OPTION_MASTER_SETS_KWA_AND_MAL                               (0, 1) {
for my $OPTION_MASTER_KWA_AND_MAL_ARE_HINTS                          (0, 1) {
for my $OPTION_REMOVE_KEY_STATUS_MESSAGE                             (0, 1) {
for my $OPTION_ITERATE_KWA_AND_MAL                                   (0, 1) {
for my $OPTION_DNP_AUTHORITY_SETS_PERMISSIBLE_KWA_AND_MAL_ALGORITHMS (0, 1) {
for my $OPTION_INCLUDE_BROADCAST_KEY                                 (0, 1) {
	my $binary
		= $OPTION_IGNORE_OUTSTATION_SEQ_ON_REQUEST_SESSION_INITIATION
		. $OPTION_MASTER_SETS_KWA_AND_MAL
		. $OPTION_MASTER_KWA_AND_MAL_ARE_HINTS
		. $OPTION_REMOVE_KEY_STATUS_MESSAGE
		. $OPTION_ITERATE_KWA_AND_MAL
		. $OPTION_DNP_AUTHORITY_SETS_PERMISSIBLE_KWA_AND_MAL_ALGORITHMS
		. $OPTION_INCLUDE_BROADCAST_KEY
		;
	my $filename = "profile-" . unpack("N", pack("B32", substr("0" x 32 . $binary, -32))) . ".hpp";
	
	unless(open FILE, '>'.$filename) {
		die "\nUnable to create $filename\n";
	}

	print FILE <<EOF
#ifndef DNP3SAV6_PROFILE_HPP_INCLUDED
#define DNP3SAV6_PROFILE_HPP_INCLUDED 1

#define OPTION_IGNORE_OUTSTATION_SEQ_ON_REQUEST_SESSION_INITIATION $OPTION_IGNORE_OUTSTATION_SEQ_ON_REQUEST_SESSION_INITIATION
#define OPTION_MASTER_SETS_KWA_AND_MAL $OPTION_MASTER_SETS_KWA_AND_MAL 
#define OPTION_MASTER_KWA_AND_MAL_ARE_HINTS ($OPTION_MASTER_KWA_AND_MAL_ARE_HINTS ? $OPTION_MASTER_SETS_KWA_AND_MAL : 0)
#define OPTION_REMOVE_KEY_STATUS_MESSAGE $OPTION_REMOVE_KEY_STATUS_MESSAGE
#define OPTION_ITERATE_KWA_AND_MAL $OPTION_ITERATE_KWA_AND_MAL
#define OPTION_DNP_AUTHORITY_SETS_PERMISSIBLE_KWA_AND_MAL_ALGORITHMS $OPTION_DNP_AUTHORITY_SETS_PERMISSIBLE_KWA_AND_MAL_ALGORITHMS
#define OPTION_INCLUDE_BROADCAST_KEY $OPTION_INCLUDE_BROADCAST_KEY

#endif
EOF

}}}}}}}

