name: CI

on:
  push:
    branches:
      - master
      - topic/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: vlinder/build-image

    steps:
    - uses: actions/checkout@v2
    - name: build and run tests
      run: |
        git submodule update --init
        mkdir .build
        cd .build
        cmake ..
        make
        CTEST_OUTPUT_ON_FAILURE=1 make test
  coverage:
    runs-on: ubuntu-18.04
    container:
            image: vlinder/build-image:topic-add-lcov

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: build and run tests
      run: |
        git submodule update --init --recursive
        mkdir .build
        cd .build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DSA_COVERAGE
        make
        make secureauthentication_coverage

