name: CI

on:
  push:
    branches:
      - master
      - topic/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: vlinder/build-image

    steps:
    - uses: actions/checkout@v2
    - name: build and run tests
      run: |
        git submodule update --init
        mkdir .build
        cd .build
        cmake ..
        make
        CTEST_OUTPUT_ON_FAILURE=1 make test
  coverage:
    runs-on: ubuntu-18.04
    container:
            image: vlinder/build-image

    steps:
    - uses: actions/checkout@v2
    - name: build and run tests
      env:
        CODECOV_TOKEN: ${{ secrets.CodeCovToken }}
      run: |
        git submodule update --init --recursive
        mkdir .build
        cd .build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DSA_COVERAGE=1
        make
        make secureauthentication_coverage
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

